### ISSUE TITLE
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### ISSUE THREAD

**Issue by cliffbueno** [AroneyS/binchicken#136]
Hello,
I was able to run the coassemble step, but was not able to run aviary in the update step. Here is the output, please let me know if you have suggestions for troubleshooting. Thank you.

INFO: Command: binchicken update --coassemble-output /scratch/alpine/clbd1748/Australia/binchicken_output2 --run-aviary --aviary-speed fast --aviary-gtdbtk-db /scratch/alpine/clbd1748/release220 --aviary-checkm2-db /projects/clbd1748/dbs/min_ref_rsdata_v1.npz --aviary-recover-cores 64 --output binchicken_update
08/14/2024 09:02:17 PM INFO: Loading inputs from old config
Traceback (most recent call last):
  File "/projects/clbd1748/miniconda3/envs/binchicken/bin/binchicken", line 10, in <module>
    sys.exit(main())
  File "/projects/clbd1748/miniconda3/envs/binchicken/lib/python3.10/site-packages/binchicken/binchicken.py", line 1500, in main
    update(args)
  File "/projects/clbd1748/miniconda3/envs/binchicken/lib/python3.10/site-packages/binchicken/binchicken.py", line 659, in update
    args.genomes = [os.path.normpath(os.path.join(args.coassemble_output, "..", v)) for _,v in old_config["genomes"].items()]
  File "/projects/clbd1748/miniconda3/envs/binchicken/lib/python3.10/site-packages/binchicken/binchicken.py", line 659, in <listcomp>
    args.genomes = [os.path.normpath(os.path.join(args.coassemble_output, "..", v)) for _,v in old_config["genomes"].items()]
  File "/projects/clbd1748/miniconda3/envs/binchicken/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/projects/clbd1748/miniconda3/envs/binchicken/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by AroneyS** [comment]
Can you send me the config in `/scratch/alpine/clbd1748/Australia/binchicken_output2`? In particular, what is in the `genomes:` section? I suspect this is a bug in update if you didn't provide genomes in the initial run. Should be an easy fix.
